name: Git Push
on:
    schedule:
        #Github Action은 레포지토리에 60일간 변경사항이 없으면 비활성화되므로, 이를 방지하기 위하여 한 달에 한 번씩 자동 Push 수행
        - cron: "0 0 1 * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Create local changes
          run: |
            date > date.txt
        - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -f .
            git commit -m "Add changes" -a
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
