name: SMB Ward
on:
    schedule:
        # 월-금 9시, 13시, 18시 정각
        # Github Action은 UTC 기준 한국시간(KST = UTC+9)에서 -9
        # github action corn 약 15분 지연 실행함
        # 최소 간격은 5분이지만, 실제로 예정된 스캐줄대로 전부 실행되지 않음(제약사항)
        # - cron: "0 0,4,9 * * 1-5"
        - cron: "*/5 * * * *" # 테스트
        

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      env:
        CHAT_BOT_TOKEN: ${{ secrets.CHAT_BOT_TOKEN }}
        CHAT_USER_ID: ${{ secrets.CHAT_USER_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python wards/smb.py
